### ISSUE TITLE
Install fails on bgen.h

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit-plink#2]
```
 x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -
c build/temp.linux-x86_64-3.6/bgen_reader._ffi.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/bgen_reader._ffi.o
    build/temp.linux-x86_64-3.6/bgen_reader._ffi.c:541:14: fatal error: bgen/bgen.h: No such file or directory
         #include "bgen/bgen.h"
                  ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
```
I tried to install here but hit a problem with bgen-reader. It looks like this requires a pip user to install the bgen C library in their system (ugh).

Any workarounds here, or is conda the only option for to get this working?

Feeling quite vindicated about the repo split right now!

**Comment by jeromekelleher** [comment]
So it seems that when we install pysnptools in the GitHub action (I tried this out in #3)  it doesn't pull in ``bgen-reader``, but for some reason when I'm installing it locally (Linux, Python 3.6) it does.

I've tried using the exact pip commands that are used in the GitHub action.

Any idea what's going on here?

**Comment by eric-czech** [comment]
Hmm, they only test it on [3.7/3.8](https://github.com/fastlmm/PySnpTools/blob/master/.travis.yml#L5) so I'm not surprised it doesn't work on 3.6.  I have no idea why it wouldn't also pull in bgen-reader on later versions (it should).

**Comment by jeromekelleher** [comment]
Aha, I tried it on Python 3.7 and it works now. Turns out there's a manylinux wheel for bgen-reader on 3.7.

Thanks for the pointers.

Do we have somewhere we declare our supported Python versions? Looks like this sets the floor at 3.7.

**Comment by eric-czech** [comment]
Good point, I'll add the constraint here like we do in the main repo: https://github.com/pystatgen/sgkit/blob/master/setup.cfg#L26.
